import type { Product } from "@/lib/products/product"

/**
 * Seed catalog. The first five rows are the ones drawn in the Figma table;
 * two more make the catalog span two pages, as the design's footer shows
 * ("Strona 1 z 2 · 7 produktów").
 */
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "mbp14m3pro",
    name: 'MacBook Pro 14"',
    sku: "MBP14M3PRO",
    description: "Laptop z układem M3 Pro, 18 GB RAM, 512 GB SSD.",
    manufacturer: "Apple",
    category: "Komputery",
    features: ["WiFi", "Bluetooth", "USB-C", "Premium"],
    priceNet: 8129.27,
    priceGross: 9999,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minCartQuantity: 1,
    maxCartQuantity: 3,
  },
  {
    id: "sgs24u256",
    name: "Galaxy S24 Ultra",
    sku: "SGS24U256",
    description: "Flagowy smartfon z rysikiem S Pen, 256 GB.",
    manufacturer: "Samsung",
    category: "Telefony",
    features: ["WiFi", "Bluetooth", "USB-C", "Wodoodporny"],
    priceNet: 5121.14,
    priceGross: 6299,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 45,
    minCartQuantity: 1,
    maxCartQuantity: 2,
  },
  {
    id: "snwh1000xm5",
    name: "Sony WH-1000XM5",
    sku: "SNWH1000XM5",
    description: "Bezprzewodowe słuchawki z aktywną redukcją szumów.",
    manufacturer: "Sony",
    category: "RTV",
    features: ["Bluetooth", "Bezprzewodowy", "Premium"],
    priceNet: 1300,
    priceGross: 1599,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minCartQuantity: 1,
    maxCartQuantity: 5,
  },
  {
    id: "bswau28p40",
    name: "Bosch Serie 6 WAU28P40",
    sku: "BSWAU28P40",
    description: "Pralka 9 kg, klasa energetyczna A.",
    manufacturer: "Bosch",
    category: "AGD",
    features: ["Ekologiczny"],
    priceNet: 2682.11,
    priceGross: 3299,
    vatRate: 23,
    currency: "PLN",
    isAvailable: false,
    isLimited: true,
    stockQuantity: 0,
    minCartQuantity: 1,
    maxCartQuantity: 1,
  },
  {
    id: "xmsb8blk",
    name: "Xiaomi Smart Band 8",
    sku: "XMSB8BLK",
    description: "Opaska fitness z ekranem AMOLED.",
    manufacturer: "Xiaomi",
    category: "Akcesoria",
    features: ["Bluetooth", "Wodoodporny"],
    priceNet: 145.53,
    priceGross: 179,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minCartQuantity: 1,
    maxCartQuantity: 10,
  },
  {
    id: "dsv15detect",
    name: "Dyson V15 Detect",
    sku: "DSV15DETECT",
    description: "Bezprzewodowy odkurzacz z laserowym wykrywaniem kurzu.",
    manufacturer: "Dyson",
    category: "AGD",
    features: ["Bezprzewodowy", "Premium"],
    priceNet: 2438.21,
    priceGross: 2999,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 12,
    minCartQuantity: 1,
    maxCartQuantity: 2,
  },
  {
    id: "lnvtp14gen5",
    name: "Lenovo ThinkPad T14 Gen 5",
    sku: "LNVTP14GEN5",
    description: "Biznesowy laptop 14\", 32 GB RAM, 1 TB SSD.",
    manufacturer: "Lenovo",
    category: "Komputery",
    features: ["WiFi", "Bluetooth", "USB-C"],
    priceNet: 6503.25,
    priceGross: 7999,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    stockQuantity: null,
    minCartQuantity: 1,
    maxCartQuantity: 5,
  },
]
